#### gBar blur ####
    layerrule = blur, ^(gtk-layer-shell)$
    layerrule = ignorezero, ^(gtk-layer-shell)$
#### \gBar blur ####

#### dunst blur ####
    layerrule = blur, ^(notifications)$
    layerrule = ignorezero, ^(notifications)$
#### \dunst blur ####

#### rofi blur ####
    layerrule = blur, ^(rofi)$
    layerrule = ignorezero, ^(rofi)$
#### \rofi blur ####
