-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--### gBar blur ####

hl.layer_rule({
    match = {
        namespace = "^(gtk-layer-shell)$",
    },
    blur = true,
    ignore_alpha = 0,
})

--### \gBar blur ####

--### dunst blur ####

hl.layer_rule({
    match = {
        namespace = "^(notifications)$",
    },
    blur = true,
    ignore_alpha = 0,
})

--### \dunst blur ####

--### rofi blur ####

hl.layer_rule({
    match = {
        namespace = "^(rofi)$",
    },
    blur = true,
    ignore_alpha = 0,
})

--### \rofi blur ####
