#### gBar blur ####
layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0
  match:namespace = ^(gtk-layer-shell)$
}
#### \gBar blur ####

#### dunst blur ####
layerrule {
  name = layerrule-2
  blur = on
  ignore_alpha = 0
  match:namespace = ^(notifications)$
}
#### \dunst blur ####

#### rofi blur ####
layerrule {
  name = layerrule-3
  blur = on
  ignore_alpha = 0
  match:namespace = ^(rofi)$
}
#### \rofi blur ####
