-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- example window rules

-- for windows named/classed as abc and xyz

--windowrule = move 69 420, abc

--windowrule = size 420 69, abc

--windowrule = tile, xyz

--windowrule = float, abc

--windowrule = pseudo, abc

hl.window_rule({
    name  = "windowrule-1",
    match = {
        class = "^(jetbrains-client)$",
    },
    workspace = "2 silent"
})

hl.window_rule({
    name  = "windowrule-2",
    match = {
        class = "^(.*Godot Engine)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    name  = "windowrule-3",
    match = {
        class = "^(teams-for-linux)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    name  = "windowrule-4",
    match = {
        class = "^(spotify)$",
    },
    workspace = "4 silent",
})

hl.window_rule({
    name  = "windowrule-5",
    match = {
        class = "^(firefox)$",
    },
    workspace = "5 silent",
})

hl.window_rule({
    name  = "windowrule-6",
    match = {
        class = "^(signal)$",
    },
    workspace = "6 silent",
})

hl.window_rule({
    name  = "windowrule-7",
    match = {
        class = "^(vesktop)$",
    },
    workspace = "6 silent",
})

hl.window_rule({
    name  = "windowrule-8",
    match = {
        class = "^(openrgb)$",
    },
    workspace = "8 silent",
})

hl.window_rule({
    name  = "windowrule-9",
    match = {
        class = "^(jetbrains-gateway)$",
    },
    workspace = "9 silent",
    tile = true,
})

--windowrule = opaque, class:^(kitty)$

--windowrule = opacity 0.6 0.6, class:^(kitty)$

--windowrule = opaque, class:^(vesktop)$

--windowrule = opacity 0.99 0.99, class:^(vesktop)$

--windowrule = bordercolor rgb(FFFFFF), class:^(vesktop)$

--old flameshot

--set flameshot to floating

--windowrule = float, class:^(flameshot)$,title:^(flameshot)

hl.window_rule({
    name  = "windowrule-10",
    match = {
        title = "flameshot",
    },
    stay_focused = true,
    rounding = 0,
    border_size = 0,
    fullscreen = true,
    move = { "(0)", "(0)" },
})

hl.window_rule({
    name  = "windowrule-11",
    match = {
        class = "flameshot",
    },
    float = true,
})

-- make Emacs float

hl.window_rule({
    name  = "windowrule-12",
    match = {
        class = "^(Emacs)$",
    },
    float = true,
})

-- flameshot multi-display fix

--windowrule = move 0 0,class:(flameshot),title:(flameshot)

--windowrule = pin,class:(flameshot),title:(flameshot)

--windowrule = fullscreenstate,class:(flameshot),title:(flameshot)

--windowrule = float,class:(flameshot),title:(flameshot)

-- float kitty based file picker

hl.window_rule({
    name  = "windowrule-13",
    match = {
        class = "^(term-file-picker)$",
    },
    float = true,
})

-- float anki windows

hl.window_rule({
    name  = "windowrule-14",
    match = {
        class = "^(anki)$",
    },
    size = { 600, 450 },
    float = true,
})

-- xwayland fixes

-- rider issues

hl.window_rule({
    name  = "windowrule-15",
    match = {
        class = "^(jetbrains-rider)$",
        title = "^(win*.)$",
    },
    no_focus = true,
    border_color = "rgb(EE4B2B)",
})

-- unity issues

--windowrule = opacity 0.8 0.8, class:^(Unity)$

hl.window_rule({
    name  = "windowrule-16",
    match = {
        class = "^(Unity)$",
    },
    opaque = true,
})

hl.window_rule({
    name  = "windowrule-17",
    match = {
        class = "^(Unity)$",
        title = "^(Color)$",
    },
    move = { "(cursor_x+(-(monitor_w*0.5)))", "(cursor_y+(-(monitor_h*0.5)))" },
})

hl.window_rule({
    name  = "windowrule-18",
    match = {
        class = "^(Unity)$",
        title = "^(Select Texture)$",
    },
    move = { "(cursor_x+(-(monitor_w*0.5)))", "(cursor_y+(-(monitor_h*0.5)))" },
})

hl.window_rule({
    name  = "windowrule-19",
    match = {
        class = "^(Unity)$",
        title = "^(UnityEditor.Searcher.SearcherWindow)$",
    },
    move = { "(cursor_x+(-(monitor_w*0.5)))", "(cursor_y+(-(monitor_h*0.5)))" },
})

hl.window_rule({
    name  = "windowrule-20",
    match = {
        class = "^(Unity)$",
        title = "^(UnityEditor.AddComponent.AddComponentWindow)$",
    },
    move = { "(cursor_x+(-(monitor_w*0.5)))", "(cursor_y+(-(monitor_h*0.5)))" },
})

hl.window_rule({
    name  = "windowrule-21",
    match = {
        class = "^(Unity)$",
        title = "^(Select Sprite)$",
    },
    move = { "(cursor_x+(-(monitor_w*0.5)))", "(cursor_y+(-(monitor_h*0.5)))" },
})

hl.window_rule({
    name  = "make-dottrace-usable",
    match = {
        class = "^$",
        title = "^$",
        float = 1,
        xwayland = 1,
    },
    no_initial_focus = 1,
})

--windowrule = stayfocused, match:class:^$, match:title:^$, match:floating:1, match:xwayland:1

--windowrule = immediate, class:^(rocketleague)$

--windowrule = bordercolor rgb(EE4B2B), class:^(Unity)$ #, tit# -- Fix odd behaviors in IntelliJ IDEs --

--! Fix focus issues when dialogs are opened or closed

-- windowrule = windowdance,class:^(jetbrains-.*)$,floating:1

--! Fix splash screen showing in weird places and prevent annoying focus takeovers

--windowrule {

--  name = windowrule-22

--  center = on

--  no_focus = on

--  border_size = 0

--  match:class = ^(jetbrains-.*)$

--  match:title = ^(splash)$

--  match:float = 1

--}

--

--

--# Try to fix weird rider issues

--windowrule {

--  name = windowrule-23

--  tag = +jbpopup

--  match:class = ^jetbrains-.+$

--  match:float = 1

--}

--windowrule = bordercolor rgb(EE4B2B), tag:jbpopup

--windowrule {

--  name = windowrule-24

--  size = 1200 1600

--  min_size = 1200 1600

--  match:tag = jbpopup

--}

--

--#windowrule = persistentsize no, tag:jbpopup

--#windowrule = tile, tag:jbpopup

--#windowrule = stayfocused, tag:jbpopup

--#windowrule = noinitialfocus, tag:jbpopup

--

--#! Center popups/find windows

--windowrule {

--  name = windowrule-25

--  center = on

--  border_size = 0

--  match:class = ^(jetbrains-.*)$

--  match:title = ^( )$

--  match:float = 1

--}

--

--#windowrule = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1

--#! Disable window flicker when autocomplete or tooltips appear

--windowrule {

--  name = windowrule-26

--  no_focus = on

--  match:class = ^(jetbrains-.*)$

--  match:title = ^(win.*)$

--  match:float = 1le:^(win*.)$

--}

-- clipse tui clipboard manager

hl.window_rule({
    name  = "windowrule-27",
    match = {
        class = "(clipse)",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-28",
    match = {
        class = "(clipse)",
    },
    size = { 1222, 1252 },
})

hl.window_rule({
    name  = "windowrule-29",
    match = {
        class = "^(steam_app_1966720)$",
    },
    immediate = true,
})

hl.window_rule({
    name  = "windowrule-30",
    match = {
        class = "^(Minecraft.*)$",
    },
    immediate = true,
})

hl.window_rule({
    name  = "windowrule-31",
    match = {
        class = "^(steam_app_252950)$",
    },
    immediate = true,
})

-- windowrule = nofullscreenrequest, class:^(firefox-work)$

-- windowrule = nomaximizerequest, class:^(firefox-work)$

--windowrulev2 = noborder, onworkspace:w[t1]

--windowrulev2 = dimaround, class:^(kitty-.*term)$

--windowrulev2 = noborder, focus:0

--windowrulev2 = noshadow, focus:0

--windowrule = tile, jetbrains-client

hl.window_rule({
    name  = "windowrule-32",
    match = {
        title = "^(.*Godot Engine)$",
    },
    tile = true,
})

-- test with pinned scratch workspaces

-- windowrule = pin, class:^(kitty-dropterm)$
