# example window rules
# for windows named/classed as abc and xyz
#windowrule = move 69 420, abc
#windowrule = size 420 69, abc
#windowrule = tile, xyz
#windowrule = float, abc
#windowrule = pseudo, abc
windowrule = workspace 2, class:^(jetbrains-client)$
windowrule = workspace 3, class:^(.*Godot Engine)$
windowrule = workspace 4, class:^(teams-for-linux)$
windowrule = workspace 4, class:^(Spotify)$
windowrule = workspace 5, class:^(firefox)$
windowrule = workspace 6, class:^(Signal)$
windowrule = workspace 6, class:^(vesktop)$
windowrule = workspace 8, class:^(openrgb)$
windowrule = workspace 9, class:^(jetbrains-gateway)$
#windowrule = opaque, class:^(kitty)$
#windowrule = opacity 0.6 0.6, class:^(kitty)$
#windowrule = opaque, class:^(vesktop)$
#windowrule = opacity 0.99 0.99, class:^(vesktop)$
#windowrule = bordercolor rgb(FFFFFF), class:^(vesktop)$

#old flameshot
#set flameshot to floating
windowrule = float,class:^(flameshot)$,title:^(flameshot)

# flameshot multi-display fix
#windowrule = move 0 0,class:(flameshot),title:(flameshot)
#windowrule = pin,class:(flameshot),title:(flameshot)
#windowrule = fullscreenstate,class:(flameshot),title:(flameshot)
#windowrule = float,class:(flameshot),title:(flameshot)

# float kitty based file picker
windowrule = float,class:^(term-file-picker)$
# float anki windows
windowrule = size 600 450, class:^(anki)$
windowrule = float, class:^(anki)$
# xwayland fixes
# rider issues
windowrule = nofocus, class:^(jetbrains-rider)$, title:^(win*.)$
windowrule = bordercolor rgb(EE4B2B), class:^(jetbrains-rider)$, title:^(win*.)$
# unity issues
#windowrule = opacity 0.8 0.8, class:^(Unity)$
windowrule = opaque, class:^(Unity)$
windowrule = move cursor -50% -50%, class:^(Unity)$, title:^(Color)$
windowrule = move cursor -50% -50%, class:^(Unity)$, title:^(Select Texture)$
windowrule = move cursor -50% -50%, class:^(Unity)$, title:^(UnityEditor.Searcher.SearcherWindow)$
windowrule = move cursor -50% -50%, class:^(Unity)$, title:^(UnityEditor.AddComponent.AddComponentWindow)$
windowrule = move cursor -50% -50%, class:^(Unity)$, title:^(Select Sprite)$
#windowrule = immediate, class:^(rocketleague)$
#windowrule = bordercolor rgb(EE4B2B), class:^(Unity)$ #, tit# -- Fix odd behaviors in IntelliJ IDEs --


#! Fix focus issues when dialogs are opened or closed
# windowrule = windowdance,class:^(jetbrains-.*)$,floating:1
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule = center,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrule = nofocus,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrule = noborder,class:^(jetbrains-.*)$,title:^(splash)$,floating:1

#! Center popups/find windows
windowrule = center,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrule = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrule = noborder,class:^(jetbrains-.*)$,title:^( )$,floating:1
#! Disable window flicker when autocomplete or tooltips appear
windowrule = nofocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1le:^(win*.)$


windowrule = immediate, class:^(steam_app_1966720)$
windowrule = immediate, class:^(Minecraft.*)$
windowrule = immediate, class:^(steam_app_252950)$

# windowrule = nofullscreenrequest, class:^(firefox-work)$
# windowrule = nomaximizerequest, class:^(firefox-work)$

#windowrulev2 = noborder, onworkspace:w[t1]
#windowrulev2 = dimaround, class:^(kitty-.*term)$
#windowrulev2 = noborder, focus:0
#windowrulev2 = noshadow, focus:0

#windowrule = tile, jetbrains-client
windowrule = tile, class:^(jetbrains-gateway)$
windowrule = tile, title:^(.*Godot Engine)$

# test with pinned scratch workspaces
# windowrule = pin, class:^(kitty-dropterm)$
