# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

background_opacity 0.7
repaint_delay 1

# kitty screen grab (nice shit)
# map ctrl+alt+up      kitten kitty_grab/grab.py
#map kitty_mod+left   no_op
#map kitty_mod+right  no_op
map ctrl+page_up     previous_tab
map ctrl+page_down   next_tab

map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down
map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right

map ctrl+shift+enter new_window_with_cwd

map ctrl+shift+t new_tab_with_cwd

map ctrl+f3 detach_window new-tab

#map alt+s            launch --type background --stdin-source=@screen copy_ansi_to_clipboard

#map kitty_mod+g launch --stdin-source=@last_cmd_output --type=overlay zsh -c "emacs --tty --alternate-editor '' <(cat /dev/stdin)"
#map kitty_mod+h launch --stdin-source=@screen_scrollback --type=overlay zsh -c "emacs --tty --alternate-editor '' <(cat /dev/stdin)"

#map kitty_mod+g launch --stdin-source=@last_cmd_output --type=overlay zsh -c "nvim -"
#map kitty_mod+h launch --stdin-source=@screen_scrollback --type=overlay zsh -c "nvim -"

# disable blip sound
enable_audio_bell no

# BEGIN_KITTY_THEME
# Catppuccin Kitty Diff Mocha
include current-theme.conf
# END_KITTY_THEME

# Remote control
allow_remote_control socket-only
listen_on unix:/tmp/kitty

# Shell integration
shell_integration enabled

# Scrollback
scrollback_lines 5000
touch_scroll_multiplier 8.0

# Additional scrollback buffer, in MB! 
# used for external scrollback, not interactive inside kitty
scrollback_pager_history_size 512 
# scrollback_pager_history_size 1000

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /home/captain/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py

# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

# Cursor settings
cursor_shape beam
cursor_underline_thickness 1
cursor_blink_interval 0.72 ease-in-out
cursor_trail 1
cursor_trail_start_threshold 0

# Experimental
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"
