# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

background_opacity 0.7
repaint_delay 1

# kitty screen grab (nice shit)
map ctrl+alt+up      kitten kitty_grab/grab.py
#map kitty_mod+left   no_op
#map kitty_mod+right  no_op
map ctrl+page_up     previous_tab
map ctrl+page_down   next_tab

map alt+s            launch --type background --stdin-source=@screen copy_ansi_to_clipboard

map kitty_mod+g launch --stdin-source=@last_cmd_output --type=overlay zsh -c "emacsclient --tty --alternate-editor '' <(cat /dev/stdin)"

# disable blip sound
enable_audio_bell no

# BEGIN_KITTY_THEME
# Catppuccin Kitty Diff Mocha
include current-theme.conf
# END_KITTY_THEME

# Remote control
allow_remote_control yes

# Scrollback
scrollback_lines 5000
touch_scroll_multiplier 8.0

# Additional scrollback buffer, in MB! 
# used for external scrollback, not interactive inside kitty
scrollback_pager_history_size 512 
# scrollback_pager_history_size 1000

# Cursor settings
cursor_shape underline
cursor_underline_thickness 1
cursor_blink_interval 0.72 ease-in-out
cursor_trail 1
cursor_trail_start_threshold 0

# Experimental
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"
