-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--# Extend based window movement ##

--### Base variables ####

local left = "left"
local right = "right"
local up = "up"
local down = "down"
local pos1 = "home"
local endkey = "end"
--$aux1  = XF86AudioPrev
local aux1 = "XF86AudioLowerVolume"
local aux2 = "XF86AudioPlay"
--$aux3  = XF86AudioNext
local aux3 = "XF86AudioRaiseVolume"
local audioplayer = "spotify"

--#### Key Matrix #####

-- $pos1 $up   $endkey   #
-- $left $down $right #
-- $aux1 $aux2 $aux3  #

--### \Key Matrix #####

--### \Base variables ####

--### Move focus ####

hl.bind("SUPER + " .. left, hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + " .. right, hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + " .. up, hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + " .. down, hl.dsp.focus({ direction = "down" }))

--### \Move focus ####

--### Move window ####

hl.bind("SUPER + SHIFT + " .. left, hl.dsp.window.swap({ direction = "left" }))
hl.bind("SUPER + SHIFT + " .. right, hl.dsp.window.swap({ direction = "right" }))
hl.bind("SUPER + SHIFT + " .. up, hl.dsp.window.swap({ direction = "up" }))
hl.bind("SUPER + SHIFT + " .. down, hl.dsp.window.swap({ direction = "down" }))

--### \Move window ####

--### Move workspace relative ####

--local function move_ws(dir, drag)
--    local matrix_size = 3
--    local active_ws = hl.monitor.focused().activeWorkspace.id
--    local row = math.floor((active_ws - 1) / matrix_size)
--    local col = (active_ws - 1) % matrix_size
--
--    -- apply direction clamping/cycling here
--    -- ...
--
--    local ws = row * matrix_size + col + 1
--    if drag then
--        hl.dsp.window.move({ workspace = ws })
--    else
--        hl.dsp.focus({ workspace = ws })
--    end
--end

local MATRIX_SIZE = 3

local function clamp(n, max)
    if n < 0 then return 0 end
    if n > max then return max end
    return n
end

local function cycle(n, size)
    return (n + size) % size
end

local function matrix_move(dir, drag)
    local active_ws = hl.get_active_workspace().id
    local matrix_max = MATRIX_SIZE - 1

    -- translate workspace ID to row/col
    local row = math.floor((active_ws - 1) / MATRIX_SIZE)
    local col = (active_ws - 1) % MATRIX_SIZE

    -- default animation style
    local anim_style = "slide"

    -- apply transformation
    if dir == "up" then
        row = clamp(row - 1, matrix_max)
        anim_style = "slidevert"
    elseif dir == "down" then
        row = clamp(row + 1, matrix_max)
        anim_style = "slidevert"
    elseif dir == "left" then
        col = clamp(col - 1, matrix_max)
    elseif dir == "right" then
        col = clamp(col + 1, matrix_max)
    end

    -- translate back to workspace ID
    local ws = row * MATRIX_SIZE + col + 1

    -- if not dragging, don't move if another monitor already shows that workspace
    --if not drag then
    --    local active_monitor = hl.get_active_monitor()
    --    local monitors = hl.get_monitors() -- or hl.monitor.list()
    --    for _, mon in ipairs(monitors) do
    --        if mon.id ~= active_monitor.id and mon.activeWorkspace.id == ws then
    --            return -- workspace already visible on another monitor
    --        end
    --    end
    --end

    -- set directional animation temporarily
    hl.animation({
        leaf = "workspaces",
        enabled = true,
        speed = 5,
        --curve = "overshot",
        bezier = "overshot",
        style = anim_style,
    })

    -- dispatch
    if drag then
        hl.dispatch(hl.dsp.window.move({ workspace = ws }))
    else
        hl.dispatch(hl.dsp.focus({ workspace = ws }))
    end

    -- reset animation to default
    hl.animation({
        leaf = "workspaces",
        enabled = true,
        speed = 5,
        bezier = "overshot",
        style = "slide",
    })
end


hl.bind("SUPER + CTRL + " .. left,  function() matrix_move("left", false) end)
hl.bind("SUPER + CTRL + " .. right, function() matrix_move("right", false) end)
hl.bind("SUPER + CTRL + " .. up,    function() matrix_move("up", false) end)
hl.bind("SUPER + CTRL + " .. down,  function() matrix_move("down", false) end)

--### \Move workspace relative ####

--### Drag window relative ####

hl.bind("SUPER + CTRL + SHIFT + " .. left,  function() matrix_move("left", true) end)
hl.bind("SUPER + CTRL + SHIFT + " .. right, function() matrix_move("right", true) end)
hl.bind("SUPER + CTRL + SHIFT + " .. up,    function() matrix_move("up", true) end)
hl.bind("SUPER + CTRL + SHIFT + " .. down,  function() matrix_move("down", true) end)

--### \Drag window relative ####

--### Jump to workspace ####

hl.bind("ALT + SUPER + " .. pos1, hl.dsp.focus({ workspace = 1 }))
hl.bind("ALT + SUPER + " .. up, hl.dsp.focus({ workspace = 2 }))
hl.bind("ALT + SUPER + " .. endkey, hl.dsp.focus({ workspace = 3 }))
hl.bind("ALT + SUPER + " .. left, hl.dsp.focus({ workspace = 4 }))
hl.bind("ALT + SUPER + " .. down, hl.dsp.focus({ workspace = 5 }))
hl.bind("ALT + SUPER + " .. right, hl.dsp.focus({ workspace = 6 }))
hl.bind("ALT + SUPER + " .. aux1, hl.dsp.focus({ workspace = 7 }))
hl.bind("ALT + SUPER + " .. aux2, hl.dsp.focus({ workspace = 8 }))
hl.bind("ALT + SUPER + " .. aux3, hl.dsp.focus({ workspace = 9 }))

--### \Jump to workspace ####

--### Jump drag window to workspace ####

hl.bind("ALT + SUPER + SHIFT + " .. pos1, hl.dsp.window.move({ workspace = 1 }))
hl.bind("ALT + SUPER + SHIFT + " .. up, hl.dsp.window.move({ workspace = 2 }))
hl.bind("ALT + SUPER + SHIFT + " .. endkey, hl.dsp.window.move({ workspace = 3 }))
hl.bind("ALT + SUPER + SHIFT + " .. left, hl.dsp.window.move({ workspace = 4 }))
hl.bind("ALT + SUPER + SHIFT + " .. down, hl.dsp.window.move({ workspace = 5 }))
hl.bind("ALT + SUPER + SHIFT + " .. right, hl.dsp.window.move({ workspace = 6 }))
hl.bind("ALT + SUPER + SHIFT + " .. aux1, hl.dsp.window.move({ workspace = 7 }))
hl.bind("ALT + SUPER + SHIFT + " .. aux2, hl.dsp.window.move({ workspace = 8 }))
hl.bind("ALT + SUPER + SHIFT + " .. aux3, hl.dsp.window.move({ workspace = 9 }))

--### \Jump drag to workspace ####

--### Audio stuff ####

--binde = CTRL, $aux1, exec, amixer -D pulse sset Master 2%-

--binde = CTRL, $aux1, exec, pamixer -d 2

hl.bind("CTRL + " .. aux1, hl.dsp.exec_cmd("playerctl -p spotify previous"))
hl.bind("CTRL + " .. aux2, hl.dsp.exec_cmd("pamixer -t"))

--binde = CTRL, $aux3, exec, amixer -D pulse sset Master 2%+

--binde = CTRL, $aux3, exec, pamixer -i 2

hl.bind("CTRL + " .. aux3, hl.dsp.exec_cmd("playerctl -p spotify next"))

--### \Audio stuff ####

--### Scratchpads ####

hl.bind("SUPER + " .. pos1, hl.dsp.exec_cmd("pypr toggle termleft"))
hl.bind("SUPER + " .. endkey, hl.dsp.exec_cmd("pypr toggle termright"))
hl.bind("SUPER + " .. aux1, hl.dsp.exec_cmd("pypr toggle workinfo"))
hl.bind("SUPER + " .. aux2, hl.dsp.exec_cmd("pypr toggle knowledge"))

--bind = SUPER SHIFT, M, exec, pypr toggle stb stb-logs

hl.bind("SUPER + " .. "A", hl.dsp.exec_cmd("pypr toggle term"))

--bind = SUPER, V, exec, pypr toggle volume

hl.bind("SUPER + " .. "V", hl.dsp.exec_cmd("pypr toggle volume"))

--### \Scratchpads ####
