## Extend based window movement ##

#### Base variables ####
    $left  = left
    $right = right
    $up    = up
    $down  = down

    $pos1  = home
    $end   = end

    #$aux1  = XF86AudioPrev
    $aux1  = XF86AudioLowerVolume
    $aux2  = XF86AudioPlay
    #$aux3  = XF86AudioNext
    $aux3  = XF86AudioRaiseVolume

    $audioplayer = spotify

    ##### Key Matrix #####
    # $pos1 $up   $end   #
    # $left $down $right #
    # $aux1 $aux2 $aux3  #
    #### \Key Matrix #####

#### \Base variables ####

#### Move focus ####
    bind = SUPER, $left , movefocus, l
    bind = SUPER, $right, movefocus, r
    bind = SUPER, $up   , movefocus, u
    bind = SUPER, $down , movefocus, d
#### \Move focus ####

#### Move window ####
    bind = SUPERSHIFT, $left , movewindow, l
    bind = SUPERSHIFT, $right, movewindow, r
    bind = SUPERSHIFT, $up   , movewindow, u
    bind = SUPERSHIFT, $down , movewindow, d
#### \Move window ####

#### Move workspace relative ####
    binde = SUPERCTRL, $left , exec, ~/.config/hypr/hyprland/scripts/matrix.sh left
    binde = SUPERCTRL, $right, exec, ~/.config/hypr/hyprland/scripts/matrix.sh right
    binde = SUPERCTRL, $up   , exec, ~/.config/hypr/hyprland/scripts/matrix.sh up
    binde = SUPERCTRL, $down , exec, ~/.config/hypr/hyprland/scripts/matrix.sh down
#### \Move workspace relative ####

#### Drag window relative ####
    binde = SUPERCTRLSHIFT, $left , exec, ~/.config/hypr/hyprland/scripts/matrix.sh left drag
    binde = SUPERCTRLSHIFT, $right, exec, ~/.config/hypr/hyprland/scripts/matrix.sh right drag
    binde = SUPERCTRLSHIFT, $up   , exec, ~/.config/hypr/hyprland/scripts/matrix.sh up drag
    binde = SUPERCTRLSHIFT, $down , exec, ~/.config/hypr/hyprland/scripts/matrix.sh down drag
#### \Drag window relative ####

#### Jump to workspace ####
    bind = ALTSUPER, $pos1,  workspace, 1
    bind = ALTSUPER, $up,    workspace, 2
    bind = ALTSUPER, $end,   workspace, 3
    bind = ALTSUPER, $left,  workspace, 4
    bind = ALTSUPER, $down,  workspace, 5
    bind = ALTSUPER, $right, workspace, 6
    bind = ALTSUPER, $aux1,  workspace, 7
    bind = ALTSUPER, $aux2,  workspace, 8
    bind = ALTSUPER, $aux3,  workspace, 9
#### \Jump to workspace ####

#### Jump drag window to workspace ####
    bind = ALTSUPERSHIFT, $pos1,  movetoworkspace, 1
    bind = ALTSUPERSHIFT, $up,    movetoworkspace, 2
    bind = ALTSUPERSHIFT, $end,   movetoworkspace, 3
    bind = ALTSUPERSHIFT, $left,  movetoworkspace, 4
    bind = ALTSUPERSHIFT, $down,  movetoworkspace, 5
    bind = ALTSUPERSHIFT, $right, movetoworkspace, 6
    bind = ALTSUPERSHIFT, $aux1,  movetoworkspace, 7
    bind = ALTSUPERSHIFT, $aux2,  movetoworkspace, 8
    bind = ALTSUPERSHIFT, $aux3,  movetoworkspace, 9
#### \Jump drag to workspace ####

#### Audio stuff ####
    #binde = CTRL, $aux1, exec, amixer -D pulse sset Master 2%-
    #binde = CTRL, $aux1, exec, pamixer -d 2
    binde = CTRL, $aux1, exec, playerctl -p $audioplayer previous
    binde = CTRL, $aux2, exec, pamixer -t
    #binde = CTRL, $aux3, exec, amixer -D pulse sset Master 2%+
    #binde = CTRL, $aux3, exec, pamixer -i 2
    binde = CTRL, $aux3, exec, playerctl -p $audioplayer next


#### \Audio stuff ####

#### Scratchpads ####
    bind = SUPER, $pos1, exec, pypr toggle termleft
    bind = SUPER, $end, exec, pypr toggle termright

    bind = SUPER, $aux1, exec, pypr toggle workinfo
    bind = SUPER, $aux2, exec, pypr toggle knowledge
    #bind = SUPER SHIFT, M, exec, pypr toggle stb stb-logs
    bind = SUPER, A, exec, pypr toggle term
    #bind = SUPER, V, exec, pypr toggle volume
    bind = SUPER, V, exec, pypr toggle volume
#### \Scratchpads ####
