## Extend based window movement ##

#### Base variables ####
    $left  = n
    $right = i
    $up    = u
    $down  = e

    $pos1  = l
    $end   = y

    $aux1  = h
    $aux2  = COMMA
    $aux3  = PERIOD

    ##### Key Matrix #####
    # $pos1 $up   $end   #
    # $left $down $right #
    # $aux1 $aux2 $aux3  #
    #### \Key Matrix #####

#### \Base variables ####

#### Move focus ####
    bind = MOD3SUPER, $left , movefocus, l
    bind = MOD3SUPER, $right, movefocus, r
    bind = MOD3SUPER, $up   , movefocus, u
    bind = MOD3SUPER, $down , movefocus, d
#### \Move focus ####

#### Move window ####
    bind = MOD3SUPERSHIFT, $left , movewindow, l
    bind = MOD3SUPERSHIFT, $right, movewindow, r
    bind = MOD3SUPERSHIFT, $up   , movewindow, u
    bind = MOD3SUPERSHIFT, $down , movewindow, d
#### \Move window ####

#### Move workspace relative ####
    binde = MOD3SUPERCTRL, $left , exec, ~/.config/hypr/hyprland/scripts/matrix.sh left
    binde = MOD3SUPERCTRL, $right, exec, ~/.config/hypr/hyprland/scripts/matrix.sh right
    binde = MOD3SUPERCTRL, $up   , exec, ~/.config/hypr/hyprland/scripts/matrix.sh up
    binde = MOD3SUPERCTRL, $down , exec, ~/.config/hypr/hyprland/scripts/matrix.sh down
#### \Move workspace relative ####

#### Drag window relative ####
    binde = MOD3SUPERCTRLSHIFT, $left , exec, ~/.config/hypr/hyprland/scripts/matrix.sh left drag
    binde = MOD3SUPERCTRLSHIFT, $right, exec, ~/.config/hypr/hyprland/scripts/matrix.sh right drag
    binde = MOD3SUPERCTRLSHIFT, $up   , exec, ~/.config/hypr/hyprland/scripts/matrix.sh up drag
    binde = MOD3SUPERCTRLSHIFT, $down , exec, ~/.config/hypr/hyprland/scripts/matrix.sh down drag
#### \Drag window relative ####

#### Jump to workspace ####
    bind = MOD3ALTSUPER, $pos1,  workspace, 1
    bind = MOD3ALTSUPER, $up,    workspace, 2
    bind = MOD3ALTSUPER, $end,   workspace, 3
    bind = MOD3ALTSUPER, $left,  workspace, 4
    bind = MOD3ALTSUPER, $down,  workspace, 5
    bind = MOD3ALTSUPER, $right, workspace, 6
    bind = MOD3ALTSUPER, $aux1,  workspace, 7
    bind = MOD3ALTSUPER, $aux2,  workspace, 8
    bind = MOD3ALTSUPER, $aux3,  workspace, 9
#### \Jump to workspace ####

#### Jump drag window to workspace ####
    bind = MOD3ALTSUPERSHIFT, $pos1,  movetoworkspace, 1
    bind = MOD3ALTSUPERSHIFT, $up,    movetoworkspace, 2
    bind = MOD3ALTSUPERSHIFT, $end,   movetoworkspace, 3
    bind = MOD3ALTSUPERSHIFT, $left,  movetoworkspace, 4
    bind = MOD3ALTSUPERSHIFT, $down,  movetoworkspace, 5
    bind = MOD3ALTSUPERSHIFT, $right, movetoworkspace, 6
    bind = MOD3ALTSUPERSHIFT, $aux1,  movetoworkspace, 7
    bind = MOD3ALTSUPERSHIFT, $aux2,  movetoworkspace, 8
    bind = MOD3ALTSUPERSHIFT, $aux3,  movetoworkspace, 9
#### \Jump drag to workspace ####

#### Scratchpads ####
    bind = MOD3ALT, $pos1, exec, pypr toggle termleft
    bind = MOD3SUPER, $end, exec, pypr toggle termright

    bind = MOD3SUPER, $aux1, exec, pypr toggle workinfo
    bind = MOD3SUPER, $aux2, exec, pypr toggle knowledge
    #bind = SUPER SHIFT, M, exec, pypr toggle stb stb-logs
    bind = SUPER, A, exec, pypr toggle term
    bind = SUPER, V, exec, pypr toggle volume
    bind = MOD3SUPER, V, exec, pypr toggle volume
#### \Scratchpads ####
