-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--# Extend based window movement ##

--### Base variables ####

local left = "left"
local right = "right"
local up = "up"
local down = "down"
local pos1 = "home"
local endkey = "end"
--$aux1  = XF86AudioPrev
local aux1 = "XF86AudioLowerVolume"
local aux2 = "XF86AudioPlay"
--$aux3  = XF86AudioNext
local aux3 = "XF86AudioRaiseVolume"
local audioplayer = "spotify"

--#### Key Matrix #####

-- $pos1 $up   $endkey   #
-- $left $down $right #
-- $aux1 $aux2 $aux3  #

--### \Key Matrix #####

--### \Base variables ####

--### Move focus ####

hl.bind("SUPER + " .. left, hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + " .. right, hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + " .. up, hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + " .. down, hl.dsp.focus({ direction = "down" }))

--### \Move focus ####

--### Move window ####

hl.bind("SUPER + SHIFT + " .. left, hl.dsp.window.swap({ direction = "left" }))
hl.bind("SUPER + SHIFT + " .. right, hl.dsp.window.swap({ direction = "right" }))
hl.bind("SUPER + SHIFT + " .. up, hl.dsp.window.swap({ direction = "up" }))
hl.bind("SUPER + SHIFT + " .. down, hl.dsp.window.swap({ direction = "down" }))

--### \Move window ####

--### Move workspace relative ####

hl.bind("SUPER + CTRL + " .. left, hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/matrix.sh left"))
hl.bind("SUPER + CTRL + " .. right, hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/matrix.sh right"))
hl.bind("SUPER + CTRL + " .. up, hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/matrix.sh up"))
hl.bind("SUPER + CTRL + " .. down, hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/matrix.sh down"))

--### \Move workspace relative ####

--### Drag window relative ####

hl.bind("SUPER + CTRL + SHIFT + " .. left, hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/matrix.sh left drag"))
hl.bind("SUPER + CTRL + SHIFT + " .. right, hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/matrix.sh right drag"))
hl.bind("SUPER + CTRL + SHIFT + " .. up, hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/matrix.sh up drag"))
hl.bind("SUPER + CTRL + SHIFT + " .. down, hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/matrix.sh down drag"))

--### \Drag window relative ####

--### Jump to workspace ####

hl.bind("ALT + SUPER + " .. pos1, hl.dsp.focus({ workspace = 1 }))
hl.bind("ALT + SUPER + " .. up, hl.dsp.focus({ workspace = 2 }))
hl.bind("ALT + SUPER + " .. endkey, hl.dsp.focus({ workspace = 3 }))
hl.bind("ALT + SUPER + " .. left, hl.dsp.focus({ workspace = 4 }))
hl.bind("ALT + SUPER + " .. down, hl.dsp.focus({ workspace = 5 }))
hl.bind("ALT + SUPER + " .. right, hl.dsp.focus({ workspace = 6 }))
hl.bind("ALT + SUPER + " .. aux1, hl.dsp.focus({ workspace = 7 }))
hl.bind("ALT + SUPER + " .. aux2, hl.dsp.focus({ workspace = 8 }))
hl.bind("ALT + SUPER + " .. aux3, hl.dsp.focus({ workspace = 9 }))

--### \Jump to workspace ####

--### Jump drag window to workspace ####

hl.bind("ALT + SUPER + SHIFT + " .. pos1, hl.dsp.window.move({ workspace = 1 }))
hl.bind("ALT + SUPER + SHIFT + " .. up, hl.dsp.window.move({ workspace = 2 }))
hl.bind("ALT + SUPER + SHIFT + " .. endkey, hl.dsp.window.move({ workspace = 3 }))
hl.bind("ALT + SUPER + SHIFT + " .. left, hl.dsp.window.move({ workspace = 4 }))
hl.bind("ALT + SUPER + SHIFT + " .. down, hl.dsp.window.move({ workspace = 5 }))
hl.bind("ALT + SUPER + SHIFT + " .. right, hl.dsp.window.move({ workspace = 6 }))
hl.bind("ALT + SUPER + SHIFT + " .. aux1, hl.dsp.window.move({ workspace = 7 }))
hl.bind("ALT + SUPER + SHIFT + " .. aux2, hl.dsp.window.move({ workspace = 8 }))
hl.bind("ALT + SUPER + SHIFT + " .. aux3, hl.dsp.window.move({ workspace = 9 }))

--### \Jump drag to workspace ####

--### Audio stuff ####

--binde = CTRL, $aux1, exec, amixer -D pulse sset Master 2%-

--binde = CTRL, $aux1, exec, pamixer -d 2

hl.bind("CTRL + " .. aux1, hl.dsp.exec_cmd("playerctl -p spotify previous"))
hl.bind("CTRL + " .. aux2, hl.dsp.exec_cmd("pamixer -t"))

--binde = CTRL, $aux3, exec, amixer -D pulse sset Master 2%+

--binde = CTRL, $aux3, exec, pamixer -i 2

hl.bind("CTRL + " .. aux3, hl.dsp.exec_cmd("playerctl -p spotify next"))

--### \Audio stuff ####

--### Scratchpads ####

hl.bind("SUPER + " .. pos1, hl.dsp.exec_cmd("pypr toggle termleft"))
hl.bind("SUPER + " .. endkey, hl.dsp.exec_cmd("pypr toggle termright"))
hl.bind("SUPER + " .. aux1, hl.dsp.exec_cmd("pypr toggle workinfo"))
hl.bind("SUPER + " .. aux2, hl.dsp.exec_cmd("pypr toggle knowledge"))

--bind = SUPER SHIFT, M, exec, pypr toggle stb stb-logs

hl.bind("SUPER + " .. "A", hl.dsp.exec_cmd("pypr toggle term"))

--bind = SUPER, V, exec, pypr toggle volume

hl.bind("SUPER + " .. "V", hl.dsp.exec_cmd("pypr toggle volume"))

--### \Scratchpads ####
