#### Mouse binds ####
    bindm = SUPER, mouse:272, movewindow
    bindm = SUPER, mouse:273, resizewindow
    bind = SUPER, mouse_down, workspace, e+1
    bind = SUPER, mouse_up, workspace, e-1
#### \Mouse binds ####


#### Window management ####
    bind = ALT, F, togglefloating
    bind = SUPER, Q, exec, uwsm app -- kitty
    bind = SUPER, C, killactive,
    bind = SUPER, F, fullscreen, 0
    bind = SUPER, J, togglesplit
    #bind = SUPER, P, pseudo,
    bind = SUPERSHIFT, F, fullscreen, 1
#### \Window management ####


#### Launchers ####
    bind = SUPER, R, exec, rofi -show drun -theme $HOME/.config/rofi/launchers/type-3/style-1.rasi -run-command "uwsm app -- {cmd}"
#### \Launchers ####


#### Hyprland ####
    bind = SUPER, M, exec, sleep 1 && pkill -9 teams-for-linux
    bind = SUPER, M, exec, uwsm stop
    #bind = SUPER, M, exec, loginctl terminate-session self
    #bind = SUPER, M, exit
#### \Hyprland ####


#### Screenshots ####
    bind = SUPER, P, exec, QT_SCALE_FACTOR=0.8  uwsm app -- flameshot gui
    bind = SUPERCTRL, P, exec, uwsm app -- normcap
    bind = SUPERSHIFT, P, exec, uwsm app -- hyprland-interactive-screenshot
    #bind = SUPER, P, exec, grim -g "$(slurp)" - | wl-copy
#### \Screenshots ####


#### XWayland Extend fix ####
    bind = SUPERSHIFT, q, exec, setxkbmap -model 'pc105awide' -layout 'us' -variant 'cmk_ed_us' -option'' -option 'misc:extend,lv5:caps_switch_lock,grp:shifts_toggle,compose:menu,misc:cmk_curl_dh' >/dev/null 2>/dev/null
#### XWayland Extend fix ####


#### Brightness control ####
    bindle = SUPER, up, exec, ~/.config/lg/changeBrightness.zsh up
    bindle = SUPER, down, exec, ~/.config/lg/changeBrightness.zsh down
    bindl = SUPERSHIFT, l, exec, ~/.config/lg/toggleDisplayBlank.zsh

    bindl = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
    bindl = , XF86MonBrightnessUp, exec, brightnessctl set +5%
#### Brightness control ####

# autoclicker
bind = SUPER, X, exec, "$(file="/tmp/click"; if test "0" = "$(cat "$file")"; then printf '1\n' > "$file"; else printf '0\n' > "$file"; fi)"

# clipboard paste
bind = MOD3, V, exec, wl-paste | wtype -
#bind = MOD3SUPER, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = MOD3SUPER, V, exec, pypr toggle copyq


# input capture
#bind = MOD3SHIFT, Q, releaseinputcapture
