-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--### Mouse binds ####

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

--### \Mouse binds ####

--### Window management ####

hl.bind("ALT + F", hl.dsp.window.float())
hl.bind("SUPER + Q", hl.dsp.exec_cmd("uwsm app -- kitty"))
hl.bind("SUPER + C", hl.dsp.window.close())
hl.bind("SUPER + F", hl.dsp.window.fullscreen())

--bind = SUPER, P, pseudo,

hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen())

--### \Window management ####

--### Launchers ####

hl.bind("SUPER + R", hl.dsp.exec_cmd("rofi -show drun -theme " .. os.getenv("HOME") .. "/.config/rofi/launchers/type-3/style-1.rasi -run-command 'uwsm app -- {cmd}'"))

--### \Launchers ####

--### Hyprland ####

hl.bind("SUPER + M", hl.dsp.exec_cmd("sleep 1 && pkill -9 teams-for-linux"))
hl.bind("SUPER + M", hl.dsp.exec_cmd("uwsm stop"))
hl.bind("SUPER + X", hl.dsp.exec_cmd("random-wallpaper.zsh"))

--bind = SUPER, M, exec, loginctl terminate-session self

--bind = SUPER, M, exit

--### \Hyprland ####

--### Screenshots ####

hl.bind("SUPER + P", hl.dsp.exec_cmd("QT_SCALE_FACTOR=0.8 uwsm app -- flameshot gui"))
hl.bind("Print", hl.dsp.exec_cmd("QT_SCALE_FACTOR=0.8 uwsm app -- flameshot gui"))
hl.bind("SUPER + CTRL + P", hl.dsp.exec_cmd("uwsm app -- normcap"))
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("uwsm app -- hyprland-interactive-screenshot"))

--bind = SUPER, P, exec, grim -g "$(slurp)" - | wl-copy

--### \Screenshots ####

--### XWayland Extend fix ####

hl.bind("SUPER + SHIFT + q", hl.dsp.exec_cmd("setxkbmap -model 'pc105awide' -layout 'us' -variant 'cmk_ed_us' -option'' -option 'misc:extend,lv5:caps_switch_lock,grp:shifts_toggle,compose:menu,misc:cmk_curl_dh' >/dev/null 2>/dev/null"))

--### XWayland Extend fix ####

--### Brightness control ####

hl.bind("SUPER + up", hl.dsp.exec_cmd("~/.config/lg/changeBrightness.zsh up"), { locked = true })
hl.bind("SUPER + down", hl.dsp.exec_cmd("~/.config/lg/changeBrightness.zsh down"), { locked = true })
hl.bind("SUPER + SHIFT + l", hl.dsp.exec_cmd("~/.config/lg/toggleDisplayBlank.zsh"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { locked = true })

--### Brightness control ####

-- autoclicker

--hl.bind("SUPER + X", hl.dsp.exec_cmd("$(file=/tmp/click ; if test  0  =  $(cat local_var_file ) ; then printf '1\\n' >  local_var_file ; else printf '0\\n' >  local_var_file ; fi)"))

-- clipboard paste

hl.bind("MOD3 + SUPER + V", hl.dsp.exec_cmd("wl-paste| wtype-"))

--bind = MOD3SUPER, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

--bind = MOD3, V, exec, pypr toggle copyq

hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("cursor-clip"))

-- input capture

--bind = MOD3SHIFT, Q, releaseinputcapture
