#### Volume control ####
    bindle = , XF86AudioLowerVolume, exec, pamixer -d 2
    bindle = , XF86AudioRaiseVolume, exec, pamixer -i 2
#### \Volume control ####


#### Direct player control ####
    $audioplayer = spotify
    bindl = , XF86AudioPlay,  exec, playerctl -p $audioplayer play-pause
    bindl = , XF86AudioPause, exec, playerctl -p $audioplayer pause
    bindl = , XF86AudioStop,  exec, playerctl -p $audioplayer stop
    bindl = , XF86AudioNext,  exec, playerctl -p $audioplayer next
    bindl = , XF86AudioPrev,  exec, playerctl -p $audioplayer previous
#### \Direct player control ####


#### Last player control ####
    bindl = SHIFT, XF86AudioPlay,  exec, playerctl play-pause
    bindl = SHIFT, XF86AudioPause, exec, playerctl pause
    bindl = SHIFT, XF86AudioStop,  exec, playerctl stop
    bindl = SHIFT, XF86AudioNext,  exec, playerctl next
    bindl = SHIFT, XF86AudioPrev,  exec, playerctl previous
#### \Last player control ####
