-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--### Volume control ####

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 2"), { locked = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 2"), { locked = true })

--### \Volume control ####

--### Direct player control ####

local audioplayer = "spotify"

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl -p spotify play-pause"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl -p spotify pause"), { locked = true })

hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl -p spotify stop"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl -p spotify next"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl -p spotify previous"), { locked = true })

--### \Direct player control ####

--### Last player control ####

hl.bind("SHIFT" .. " + " .. "XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("SHIFT" .. " + " .. "XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"), { locked = true })

hl.bind("SHIFT" .. " + " .. "XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true })

hl.bind("SHIFT" .. " + " .. "XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("SHIFT" .. " + " .. "XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--### \Last player control ####
