#### Laptop lid closed detection ####
    bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off
    bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on
#### \Laptop lid closed detection ####
