#### Custom layer: Passthrough so Hyprland doesn't swallow keys ####
    bind = SUPER, F1, exec, dunstify "yeee boiii" "Activated Passthrough!" -t 0 -h string:x-dunst-stack-tag:layer -r 420
    bind = SUPER, F1, submap, passthrough
    submap = passthrough
        bind = SUPER, Escape, exec, dunstify -C 420
        bind = SUPER, Escape, submap, reset
    submap = reset
#### \Custom layer: Passthrough ####


#### Custom layer: Resize and move windows ####
    bind = MOD3SUPER, space, exec, dunstify "yeee boiii" "Activated super special layer" -t 0 -h string:x-dunst-stack-tag:layer -r 187
    bind = MOD3SUPER, space, submap, resize

    # will start a submap called "resize"
    submap = resize

        # sets repeatable binds for resizing the active window
        binde = MOD3SUPER, n, resizeactive, -20 0
        binde = MOD3SUPER, u, resizeactive, 0 -20
        binde = MOD3SUPER, i, resizeactive, 20 0
        binde = MOD3SUPER, e, resizeactive, 0 20
        binde = MOD3SUPER, ie, resizeactive, 20 20

        # sets repeatable binds to move the active window
        binde = MOD3SUPERCTRL, n, moveactive, -20 0
        binde = MOD3SUPERCTRL, i, moveactive, 20 0
        binde = MOD3SUPERCTRL, u, moveactive, 0 -20
        binde = MOD3SUPERCTRL, e, moveactive, 0 20

        # use reset to go back to the global submap
        bind = MOD3, Q, exec, dunstify -C 187 
        bind = MOD3, Q, submap, reset 

    # will reset the submap, meaning end the current one and return to the global one
    submap = reset
#### \Custom layer: Resize ####
