-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--### Custom layer: Passthrough so Hyprland doesn't swallow keys ####

hl.bind("SUPER + F1", hl.dsp.exec_cmd("dunstify yeee boiii Activated Passthrough! -t 0 -h string:x-dunst-stack-tag:layer -r 420"))

hl.bind("SUPER + F1", hl.dsp.submap("passthrough"))

hl.define_submap("passthrough", function()
    hl.bind("SUPER + Escape", hl.dsp.exec_cmd("dunstify -C 420"))
    hl.bind("SUPER + Escape", hl.dsp.submap("reset"))
end)


--### \Custom layer: Passthrough ####

--### Custom layer: Resize and move windows ####

hl.bind("MOD3 + SUPER + space", hl.dsp.exec_cmd("dunstify yeee boiii Activated super special layer -t 0 -h string:x-dunst-stack-tag:layer -r 187"))

hl.bind("MOD3 + SUPER + space", hl.dsp.submap("resize"))

-- will start a submap called "resize"

hl.define_submap("resize", function()
    -- sets repeatable binds for resizing the active window
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("MOD3SUPER + n", hl.dsp.resizeactive("-20 0"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("MOD3SUPER + u", hl.dsp.resizeactive("0 -20"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("MOD3SUPER + i", hl.dsp.resizeactive("20 0"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("MOD3SUPER + e", hl.dsp.resizeactive("0 20"))
    -- TODO: manual review (unknown dispatcher: resizeactive)
    -- hl.bind("MOD3SUPER + ie", hl.dsp.resizeactive("20 20"))
    -- sets repeatable binds to move the active window
    -- TODO: manual review (unknown dispatcher: moveactive)
    -- hl.bind("MOD3SUPERCTRL + n", hl.dsp.moveactive("-20 0"))
    -- TODO: manual review (unknown dispatcher: moveactive)
    -- hl.bind("MOD3SUPERCTRL + i", hl.dsp.moveactive("20 0"))
    -- TODO: manual review (unknown dispatcher: moveactive)
    -- hl.bind("MOD3SUPERCTRL + u", hl.dsp.moveactive("0 -20"))
    -- TODO: manual review (unknown dispatcher: moveactive)
    -- hl.bind("MOD3SUPERCTRL + e", hl.dsp.moveactive("0 20"))
    -- use reset to go back to the global submap
    hl.bind("MOD3 + Q", hl.dsp.exec_cmd("dunstify -C 187"))
    hl.bind("MOD3 + Q", hl.dsp.submap("reset"))
    -- will reset the submap, meaning end the current one and return to the global one
end)


--### \Custom layer: Resize ####
