git:
  diffRenderers:
    - command: delta --dark --paging=never
      colorArg: always
    - command: delta --dark --paging=never --diff-so-fancy
      colorArg: always
    - command: difft --color=always --display=inline
      type: extDiff
  autoFetch: false
