source = hyprland/mocha.conf

source = hyprland/monitors/01-source.conf
source = hyprland/binds/01-source.conf
source = hyprland/rules/01-source.conf

source = hyprland/env.conf
source = hyprland/exec-once.conf
source = hyprland/general.conf
source = hyprland/input.conf
source = hyprland/kando.conf
source = hyprland/mocha.conf
source = hyprland/plugins.conf
source = hyprland/random.conf
