[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "shift_monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.stb]
animation = "fromBottom"
command = "kitty --class kitty-stb sstb"
class = "kitty-stb"
lazy = true
size = "75% 45%"

[scratchpads.stb-logs]
animation = "fromTop"
command = "kitty --class kitty-stb-logs stbLog"
class = "kitty-stb-logs"
lazy = true
size = "75% 40%"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.termleft]
animation = "fromLeft"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
# position = "40% 30%"
lazy = true
size = "45% 90%"

[scratchpads.termright]
animation = "fromRight"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
# position = "50% 20%"
# margin = 100
lazy = true
size = "45% 90%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "47% 90%"

[scratchpads.workinfo]
animation = "fromRight"
command = "firefox --no-remote --kiosk -P work --name firefox-work ~/Downloads/LöschweitergabeAnnotated.pdf"
class = "firefox-work"
lazy = true
size = "40% 90%"

[monitors]
unknown = "wlrlui"
