source = binds/01-source.conf
source = rules/01-source.conf

source = 02-env.conf
source = 03-exec-once.conf
source = 04-plugins.conf
source = 05-mocha.conf
source = 10-general.conf
source = 11-input.conf
source = 90-kando.conf
source = 99-random.conf
