#### Wayland jank ####
    env = MOZ_ENABLE_WAYLAND,1
    env = MOZ_DISABLE_RDD_SANDBOX,1
    env = WLR_DRM_NO_ATOMIC,1
    env = GDK_BACKEND,wayland,x11
    env = QT_QPA_PLATFORM,wayland;xcb
    #env = SDL_VIDEODRIVER,wayland
    env = CLUTTER_BACKEND,wayland
    env = XDG_CURRENT_DESKTOP,Hyprland
    env = XDG_SESSION_TYPE,wayland
    env = XDG_SESSION_DESKTOP,Hyprland

    env = QT_AUTO_SCREEN_SCALE_FACTOR,1
    env = QT_QPA_PLATFORM,wayland;xcb
    env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
    env = QT_QPA_PLATFORMTHEME,qt5ct
#### \Wayland jank ####

#### Themes ####
    env = HYPRCURSOR_THEME,rose-pine-hyprcursor
    env = HYPRCURSOR_SIZE,24
    env = XCURSOR_THEME,rose-pine-hyprcursor
    env = XCURSOR_SIZE,24
# env = ENABLE_DEVICE_CHOOSER_LAYER=1 VULKAN_DEVICE_INDEX=0

#### Program vars ####
    env = GOPATH,/home/lap/.local/share/go
#### \Program vars ####

#### Deprecated shit that might be useful but likely isn't ####
    #env = HYPRLAND_LOG_WLR, 1
    ##env = GBM_BACKEND, nvidia-drm
    #env = EGL_PLATFORM, wayland
    ##env = WLR_NO_HARDWARE_CURSORS, 1
    #env = __GL_GSYNC_ALLOWED, 1
    #env = __GL_VRR_ALLOWED, 1
    ##env = LIBVA_DRIVER_NAME, iHD
    ##env = NVD_BACKEND, direct
    ##env = MOZ_DRM_DEVICE, /dev/dri/renderD129
    #env = MOZ_ENABLE_WAYLAND, 1
    #env = MOZ_DISABLE_RDD_SANDBOX, 1
    #env = THEME_DIR, /usr/share/themes/Catppuccin-Mocha-Standard-Lavender-Dark
    #env = GTK_THEME, Catppuccin-Mocha-Standard-Sapphire-Dark
    #env = GTK_USE_PORTAL=1 
    env = STEAM_FORCE_DESKTOPUI_SCALING, 1.5
    #env = HYPRCURSOR_THEME,adwaita
    #env = HYPRCURSOR_SIZE,24
    #env = XCURSOR_THEME, Catppuccin-Mocha-Sapphire-Cursors
    #env = XCURSOR_SIZE, 16
    ##env = QT_QPA_PLATFORM, wayland;xcb
    #env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
    #env = QT_QPA_PLATFORMTHEME, qt5ct
    ##env = GDK_BACKEND, wayland, x11
    ##env = XDG_CURRENT_DESKTOP, Hyprland
    #env = XDG_SESSION_TYPE, wayland
    ##env = XDG_SESSION_DESKTOP, Hyprland
    #env = WLR_DRM_NO_ATOMIC, 1
    
    # env = WLR_DRM_DEVICES,/home/lap/.config/hypr/gpus/igpu:/home/lap/.config/hypr/gpus/dgpu
#### \Deprecated shit that might be useful but likely isn't ####
