-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--### Social ####


--exec-once = [noinitialfocus] uwsm app -- teams-for-linux.desktop


--### \Social ####

--### General ####



--### \General ####

--### Background Services ####



--### Screenshots ####



--### \Screenshots ####

--### System ####




--### \System ####

--### Clipboard ####

--exec-once = uwsm app -- copyq --start-server


-- clipboard with cliphist

--exec-once = wl-paste --type text --watch cliphist store #Stores only text data

--exec-once = wl-paste --type image --watch cliphist store #Stores only image data

-- old clipboard with clipman

--exec-once = wl-paste -t text --watch clipman store 1>> ~/.cache/wl-paste.log 2>&1

--exec-once = wl-paste -p -t text --watch clipman  store -P --histpath = "~/.local/share//clipman-primary.json"

--### \Clipboard ####

--### \Background Services ####

--### Idle timeout ####

-- idle timeout

--exec-once = swayidle -w timeout 600 "swaylock" before-sleep "swaylock"           # lock screen after 10 min of idle

--exec-once = swayidle -w timeout 600 "systemctl suspend-then-hibernate"             # sleep after 10 mins of idle

--### \Idle timeout ####

--### Autostarts with hot reloads ####

-- gBar



-- dunst


-- pypr



--### \Autostarts with hot reloads ####

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("[noinitialfocus] uwsm app -- signal.desktop")
    hl.exec_cmd("[noinitialfocus] uwsm app -- vesktop.desktop")
    hl.exec_cmd("[noinitialfocus] uwsm app -- spotify-launcher.desktop")
    hl.exec_cmd("uwsm app -- firefox")
    hl.exec_cmd("uwsm app -- arrpc")
    hl.exec_cmd("uwsm app -- kdeconnectd")
    hl.exec_cmd("uwsm app -- flameshot")
    hl.exec_cmd("uwsm app -- normcap --background-mode")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("cursor-clip --daemon")
    hl.exec_cmd("ls ~/.config/gBar/style.scss| uwsm app -- entr -pns sass ~/.config/gBar/style.scss > ~/.config/gBar/style.css")
    hl.exec_cmd("ls ~/.config/gBar/style.css ~/.config/gBar/config| uwsm app -- entr -nrs systemctl --user restart gBar")
    hl.exec_cmd("ls ~/.config/dunst/dunstrc| uwsm app -- entr -nrs dunst")
    hl.exec_cmd("pypr")
    hl.exec_cmd("ls ~/.config/pypr/config.toml| uwsm app -- entr -nrs pypr reload")
end)
