#### System ####
    exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
    exec-once = /usr/lib/polkit-kde-authentication-agent-1
    exec-once = hyprpm reload -n
#### \System ####


#### Social ####
    exec-once = signal-desktop
    exec-once = teams-for-linux
    exec-once = vesktop
    exec-once = arrpc
#### \Social ####


#### General ####
    exec-once = hyprpaper
    exec-once = /usr/lib/kdeconnectd
    exec-once = spotify
    exec-once = firefox
#### \General ####


#### Screenshots ####
    exec-once = flameshot
    exec-once = normcap --background-mode
#### \Screenshots ####


#### Clipboard ####
    exec-once = copyq --start-server
    # clipboard with cliphist
    #exec-once = wl-paste --type text --watch cliphist store #Stores only text data
    #exec-once = wl-paste --type image --watch cliphist store #Stores only image data
    
    # old clipboard with clipman
    #exec-once = wl-paste -t text --watch clipman store 1>> ~/.cache/wl-paste.log 2>&1
    #exec-once = wl-paste -p -t text --watch clipman  store -P --histpath = "~/.local/share//clipman-primary.json"
#### \Clipboard ####


#### Idle timeout ####
    # idle timeout
    #exec-once = swayidle -w timeout 600 "swaylock" before-sleep "swaylock"           # lock screen after 10 min of idle
    #exec-once = swayidle -w timeout 600 "systemctl suspend-then-hibernate"             # sleep after 10 mins of idle
#### \Idle timeout ####


#### Autostarts with hot reloads ####
    # gBar
    exec-once = ls ~/.config/gBar/style.scss | entr -pns "sass ~/.config/gBar/style.scss > ~/.config/gBar/style.css"
    exec-once = ls ~/.config/gBar/style.css ~/.config/gBar/config | entr -nrs "systemctl --user restart gBar"
    
    # dunst
    exec-once = ls ~/.config/dunst/dunstrc | entr -nrs "dunst"
    
    # pypr
    exec-once = pypr
    exec-once = ls ~/.config/hypr/pyprland.toml | entr -nrs "pypr reload"
#### \Autostarts with hot reloads ####
