-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- expo plugin

--bind = SUPER, grave, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable
