-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local rosewater = "0xfff5e0dc"

local flamingo = "0xfff2cdcd"

local pink = "0xfff5c2e7"

local mauve = "0xffcba6f7"

local red = "0xfff38ba8"

local maroon = "0xffeba0ac"

local peach = "0xfffab387"

local green = "0xffa6e3a1"

local teal = "0xff94e2d5"

local sky = "0xff89dceb"

local sapphire = "0xff74c7ec"

local blue = "0xff89b4fa"

local lavender = "0xffb4befe"

local text = "0xffcdd6f4"

local subtext1 = "0xffbac2de"

local subtext0 = "0xffa6adc8"

local overlay2 = "0xff9399b2"

local overlay1 = "0xff7f849c"

local overlay0 = "0xff6c7086"

local surface2 = "0xff585b70"

local surface1 = "0xff45475a"

local surface0 = "0xff313244"

local base = "0xff1e1e2e"

local mantle = "0xff181825"

local crust = "0xff11111b"
