-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 15,
        border_size = 2,
        allow_tearing = true,
        --apply_sens_to_raw = 0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)
        -- damage_tracking = full # leave it on full unless you hate your GPU and want to make it suffer
        col = {
            active_border = { colors = { "rgba(8822bbff)", "rgba(2222bbff)" }, angle = 30 },
            inactive_border = "rgba(333333aa)",
        },
    },
    cursor = {
        inactive_timeout = 1,
    },
    xwayland = {
        force_zero_scaling = true,
    },
    decoration = {
        rounding = 10,
        blur = {
            size = 3,
            -- minimum 1
            passes = 3,
            -- minimum 1
            new_optimizations = 1,
            brightness = 0.7,
            contrast = 1.3,
            -- vibrancy = 0.2
            ignore_opacity = true,
        },
        shadow = {
            color = "0xbb1a0a1a",
            color_inactive = "0x881a1a1a",
            range = 20,
            render_power = 2,
        },
        dim_inactive = true,
        dim_strength = 0.1,
        --inactive_opacity = 0.9
        dim_special = 0.2,
    },
    animations = {
        enabled = 1,
        --animation=windows,1,5,bounce,slide
    },
    dwindle = {
        split_width_multiplier = 1.25,
        preserve_split = 1,
    },
    -- TODO: manual review: gesture = 3, "horizontal", "workspace"
    --gestures = {
    --    workspace_swipe_forever = true,
    --    workspace_swipe_min_speed_to_force = 5,
    --    workspace_swipe_distance = 200,
    --    workspace_swipe_direction_lock = false,
    --},
    xwayland = {
        force_zero_scaling = true,
    },
    misc = {
        disable_splash_rendering = true,
        --    no_direct_scanout = false
        enable_anr_dialog = false,
        vrr = 0,
        animate_manual_resizes = false,
        enable_swallow = true,
        swallow_regex = "^(Alacritty|kitty|footclient)$",
        swallow_exception_regex = "^(wev)$",
        focus_on_activate = true,
    },
    debug = {
        disable_logs = false,
    },
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },
})

-- TODO: manual review: gesture = 3, "horizontal", "workspace"
hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "overshot", style = "slide" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "overshot", style = "slide" })

hl.curve("slow", {
    type = "bezier",
    points = { { 0, 0.85 }, { 0.3, 1 } },
})

hl.curve("overshot", {
    type = "bezier",
    points = { { 0.7, 0.6 }, { 0.1, 1.1 } },
})

hl.curve("bounce", {
    type = "bezier",
    points = { { 1, 1.6 }, { 0.1, 0.85 } },
})

hl.curve("slingshot", {
    type = "bezier",
    points = { { 1, -1 }, { 0.9, 1.25 } },
})

hl.curve("nice", {
    type = "bezier",
    points = { { 0, 2 }, { 0.5, -1 } },
})
