-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    input = {
        kb_model = "pc105",
        kb_layout = "eu",
        repeat_rate = 75,
        repeat_delay = 150,
        kb_rules = "evdev",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            disable_while_typing = false,
            clickfinger_behavior = true,
        },
        touchdevice = {
            output = "DP-5",
        },
        tablet = {
            output = "DP-5",
        },
        sensitivity = -1,
        -- -1.0 - 1.0, 0 means no modification.
    },
})
