input {
    kb_model = pc105
    kb_layout = eu
    
    repeat_rate = 75
    repeat_delay = 150

    kb_file =
    kb_rules = evdev

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = no
        clickfinger_behavior = yes
    }

    touchdevice {
        output = DP-5
    }

    tablet {
        output = DP-5
    }

    sensitivity = -1 # -1.0 - 1.0, 0 means no modification.
}
