# pie
windowrule {
  name = kando
  no_blur = on
  border_size = 0
  no_anim = on
  center = on
  size = (monitor_w*1) (monitor_h*1)
  match:class = ^(kando)$
}


#bind = CTRL, Space, global, kando:prototype_trigger
