-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- pie

hl.window_rule({
    name  = "kando",
    match = {
        class = "^(kando)$",
    },
    no_blur = true,
    border_size = 0,
    no_anim = true,
    center = true,
    size = { "(monitor_w*1)", "(monitor_h*1)" },
})

--bind = CTRL, Space, global, kando:prototype_trigger
