# nice idea
windowrule = float,class:(qalculate-gtk)
windowrule = workspace special:calculator,class:(qalculate-gtk)
bind = SUPER, I, exec, pgrep qalculate-gtk && hyprctl dispatch togglespecialworkspace calculator || qalculate-gtk &
