# nice idea
windowrule {
  name = qalculate
  float = on
  workspace = special:calculator
  match:class = (qalculate-gtk)
}

bind = SUPER, I, exec, pgrep qalculate-gtk && hyprctl dispatch togglespecialworkspace calculator || qalculate-gtk &
