-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- nice idea

hl.window_rule({
    name  = "qalculate",
    match = {
        class = "(qalculate-gtk)",
    },
    float = true,
    workspace = "special:calculator",
})

hl.bind("SUPER" .. " + " .. "I", hl.dsp.exec_cmd("pgrep qalculate-gtk && hyprctl dispatch togglespecialworkspace calculator || qalculate-gtk &"))
