-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    misc = {
        disable_hyprland_logo = true,
        mouse_move_enables_dpms = false,
        key_press_enables_dpms = false,
    },
})

-- Create a fallback dummy monitor that persists

hl.monitor({
    output   = "FALLBACK",
    mode     = "1920x1080@60",
    position = "0x0",
    scale    = 1,
})
