input {
    kb_model = pc105awide
    kb_layout = us
    kb_variant = cmk_ed_us
    kb_options = misc:extend, lv5:caps_switch_lock, grp:shifts_toggle, compose:menu, misc:cmk_curl_dh 
    
    repeat_rate = 75
    repeat_delay = 150

    kb_file =
    kb_rules = evdev

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = no
        clickfinger_behavior = yes
    }

    touchdevice {
        output = DP-5
    }

    tablet {
        output = DP-5
    }
    

    sensitivity = 0.0 # -1.0 - 1.0, 0 means no modification.
}
