-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--### tamplep specific vars ####

--env = MOZ_ENABLE_WAYLAND,1

--### \tamplep specific vars ####
