## Plugins ##
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on  = "<C-n>"
run = '''
  shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''

[[mgr.prepend_keymap]]
on = ["h", "h"]
run = "plugin time-travel -- prev"
desc = "Go to previous snapshot"

[[mgr.prepend_keymap]]
on = ["h", "n"]
run = "plugin time-travel -- next"
desc = "Go to next snapshot"

[[mgr.prepend_keymap]]
on = ["h", "e"]
run = "plugin time-travel -- exit"
desc = "Exit browsing snapshots"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

## \Plugins ##

## Preview ##

[[mgr.prepend_keymap]]
on  = "<S-Up>"
run = "seek -5"

[[mgr.prepend_keymap]]
on  = "<S-Down>"
run = "seek 5"

[[mgr.prepend_keymap]]
on   = "<C-s>"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

## \Preview ##

## Quick nav ##

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/dumpster"
desc = "Cd to ~/dumpster"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "e" ]
run  = "cd ~/deckenburg"
desc = "Cd to ~/deckenburg"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "d" ]
run  = "cd ~/deckenburg/documents"
desc = "Cd to ~/deckenburg/documents"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "g" ]
run  = "cd ~/deckenburg/git"
desc = "Cd to ~/deckenburg/git"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "n", "n" ]
run  = "cd ~/deckenburg/notes"
desc = "Cd to ~/deckenburg/notes"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "n", "f" ]
run  = "cd ~/deckenburg/notes/todo/fixesnguides"
desc = "Cd to ~/deckenburg/notes/todo/fixesnguides"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "n", "t", "t" ]
run  = "cd ~/deckenburg/notes/todo-private"
desc = "Cd to ~/deckenburg/notes/todo-private"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "n", "t", "w" ]
run  = "cd ~/deckenburg/notes/todo-work"
desc = "Cd to ~/deckenburg/notes/todo-work"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "y" ]
run  = "cd ~/deckenburg/synch"
desc = "Cd to ~/deckenburg/synch"

[[mgr.prepend_keymap]]
on   = [ "g", "e", "o" ]
run  = "cd ~/deckenburg/osna"
desc = "Cd to ~/deckenburg/osna"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/.ssh"
desc = "Cd to ~/.ssh"

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "cd ~/.local"
desc = "Cd to ~/.local"

[[mgr.prepend_keymap]]
on   = [ "g", "c", "c" ]
run  = "cd ~/.config"
desc = "Cd to ~/.config"

[[mgr.prepend_keymap]]
on   = [ "g", "c", "z" ]
run  = "cd ~/.config/zsh"
desc = "cd to ~/.config/zsh"

[[mgr.prepend_keymap]]
on   = [ "g", "c", "g" ]
run  = "cd ~/.config/gBar"
desc = "cd to ~/.config/gBar"

[[mgr.prepend_keymap]]
on   = [ "g", "c", "y" ]
run  = "cd ~/.config/yazi"
desc = "cd to ~/.config/yazi"

[[mgr.prepend_keymap]]
on   = [ "g", "c", "h" ]
run  = "cd ~/.config/hypr"
desc = "cd to ~/.config/hypr"

[[mgr.prepend_keymap]]
on   = [ "g", "a" ]
run  = "cd ~/.cache"
desc = "Cd to ~/.cache"

## \Quick nav ##
