-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- monitor = , 3440x1440@144, auto, 1

hl.monitor({
    output   = "desc:Samsung Electric Company SAMSUNG 0x00000001",
    mode     = "1920x1080@60",
    position = "2048x0",
    scale    = 1,
})

hl.monitor({
    output   = "desc:LG Electronics LG TV SSCR2 0x01010101",
    mode     = "3840x2160@120",
    position = "2048x0",
    scale    = 1.25,
})

--monitor = desc:LG Electronics LG TV SSCR2 0x01010101, 3840x2160@60, 2048x0, 1.25

hl.monitor({
    output   = "desc:DENON Ltd. DENON-AVR 0x01010101",
    mode     = "3840x2160@120",
    position = "2048x0",
    scale    = 2,
})

hl.monitor({
    output   = "desc:Philips Consumer Electronics Company PHL 288E2 UK52316001405",
    mode     = "3840x2160@60",
    position = "2048x0",
    scale    = 2,
})

--monitor = desc:DENON Ltd. DENON-AVR 0x01010101, 1920x1080@120, 2048x0, 2

-- explanation for the offset: 

-- 3440 is the width of the

hl.monitor({
    output   = "desc:AOC U34G2G4R3 0x00000322",
    mode     = "3440x1440@144",
    position = "-696x-1440",
    scale    = 1,
})

--monitor = DP-3, 1920x1080@60, -1000x-1080, 1

--monitor = DP-3, 3840x2160@60, -1500x-2160, 2

--monitor = DP-4, 1920x1080@60, -696x-1080, 1

hl.monitor({
    output   = "desc:Dell Inc. DELL U3821DW F5STZ63",
    mode     = "3840x1600@60",
    position = "-896x-1600",
    scale    = 1,
})

hl.monitor({
    output   = "desc:Dell Inc. DELL U3821DW JPQTZ63",
    mode     = "3840x1600@60",
    position = "-896x-1600",
    scale    = 1,
})

hl.monitor({
    output   = "desc:Dell Inc. DELL U3821DW F6GSZ63",
    mode     = "3840x1600@60",
    position = "-896x-1600",
    scale    = 1,
})

--monitor = desc:Seiko Epson Corporation EPSON PJ 0x01010101, 3840x2160@60, 0x1728, 1.25

--monitor = desc:Seiko Epson Corporation EPSON PJ 0x01010101, 1920x1080@120, 0x-1080, 1

--monitor = desc:Seiko Epson Corporation EPSON PJ 0x01010101, 3840x2160@120, 0x-1080, 2

--monitor = desc:Seiko Epson Corporation EPSON PJ 0x01010101, 3840x2160@120, 0x-1728, 1.25

--monitor = desc:Seiko Epson Corporation EPSON PJ 0x01010101, 3840x2160@120, 0x0, 1.25, mirror, HDMI-A-1

hl.monitor({
    output   = "desc:Seiko Epson Corporation EPSON PJ 0x01010101",
    mode     = "disabled",
    position = "auto",
    scale    = 1,
})

--monitor = desc:AOC 24G1WG4 0x000488B3, 1920x1080@144, -1920x0, 1

--monitor = desc:DENON Ltd. DENON-AVR 0x01010101, 1920x1080@200, 2048x0, 1

--monitor = desc:DENON Ltd. DENON-AVR 0x01010101, 3840x2160@60, 2048x0, 1

--monitor = desc:BNQ BenQ PJ 0x00000001, 1920x1080@240, 2048x0, 1

--monitor = desc:BNQ BenQ PJ 0x00000001, 3840x2160@60, 2048x0, 1

--monitor = DP-4, 3440x1440@144, -696x-1440, 1

--monitor = DP-3, 3840x2160@30, -1500x-2160, 1

-- weird numbers because of the 1.25 scaling of the main display

--monitor = DP-5, 1920x1080@60, 64x-1080, 1

--monitor = DP-5, 1920x1080@60, 64x-1080, 1

--monitor = DP-5, 3840x2160@60, -896x-1600, 1

--monitor = DP-4, 3840x1600@60, -896x-1600, 1

--monitor = HDMI-A-1, 1920x1080@60, auto, 1

--monitor = HDMI-A-1, 3840x2160@60, 1000x1600, 1
