-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 15,
        border_size = 2,
        allow_tearing = true,
        --apply_sens_to_raw = 0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)
        -- damage_tracking = full # leave it on full unless you hate your GPU and want to make it suffer
        col = {
            active_border = { colors = { "rgba(8822bbff)", "rgba(2222bbff)" }, angle = 30 },
            inactive_border = "rgba(333333aa)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        blur = {
            size = 3,
            -- minimum 1
            passes = 3,
            -- minimum 1
            new_optimizations = 1,
            brightness = 0.7,
            contrast = 1.3,
            -- vibrancy = 0.2
            ignore_opacity = true,
        },
        shadow = {
            color = "0xbb1a0a1a",
            color_inactive = "0x881a1a1a",
            range = 20,
            render_power = 2,
        },
        dim_inactive = true,
        dim_strength = 0.1,
        --inactive_opacity = 0.9
        dim_special = 0.2,
    },
})
